// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSzKolcv3L7IuIEU2kMPkmX2CFUkOQFWY',
    appId: '1:813670334042:web:c91bd33ff07b8090bfe263',
    messagingSenderId: '813670334042',
    projectId: 'menuplanner-4980c',
    authDomain: 'menuplanner-4980c.firebaseapp.com',
    storageBucket: 'menuplanner-4980c.appspot.com',
    measurementId: 'G-9VJ17N7PC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGl5VrY17Nwl_gLH-cnEFsPaJP9b1u4bg',
    appId: '1:813670334042:android:5b9191617a0eb9b1bfe263',
    messagingSenderId: '813670334042',
    projectId: 'menuplanner-4980c',
    storageBucket: 'menuplanner-4980c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCek8108qsXunW-_0rWMX8VV5EeKW-xddk',
    appId: '1:813670334042:ios:fee5b663cdc4cd39bfe263',
    messagingSenderId: '813670334042',
    projectId: 'menuplanner-4980c',
    storageBucket: 'menuplanner-4980c.appspot.com',
    iosBundleId: 'com.example.menuPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCek8108qsXunW-_0rWMX8VV5EeKW-xddk',
    appId: '1:813670334042:ios:fee5b663cdc4cd39bfe263',
    messagingSenderId: '813670334042',
    projectId: 'menuplanner-4980c',
    storageBucket: 'menuplanner-4980c.appspot.com',
    iosBundleId: 'com.example.menuPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSzKolcv3L7IuIEU2kMPkmX2CFUkOQFWY',
    appId: '1:813670334042:web:b27b216cd2319825bfe263',
    messagingSenderId: '813670334042',
    projectId: 'menuplanner-4980c',
    authDomain: 'menuplanner-4980c.firebaseapp.com',
    storageBucket: 'menuplanner-4980c.appspot.com',
    measurementId: 'G-KY53KMSMR6',
  );

}